// <auto-generated />
using System;
using GithubSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GithubSync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GithubSync.Infrastructure.Persistence.Models.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssigneeLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Repository", "GitHubIssueId")
                        .IsUnique();

                    b.HasIndex("Repository", "Number");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("GithubSync.Infrastructure.Persistence.Models.IssueLabel", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LabelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IssueId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("IssueLabels");
                });

            modelBuilder.Entity("GithubSync.Infrastructure.Persistence.Models.Label", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Repository", "Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("GithubSync.Infrastructure.Persistence.Models.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Repository")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("GithubSync.Infrastructure.Persistence.Models.IssueLabel", b =>
                {
                    b.HasOne("GithubSync.Infrastructure.Persistence.Models.Issue", "Issue")
                        .WithMany("IssueLabels")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GithubSync.Infrastructure.Persistence.Models.Label", "Label")
                        .WithMany("IssueLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("GithubSync.Infrastructure.Persistence.Models.Issue", b =>
                {
                    b.Navigation("IssueLabels");
                });

            modelBuilder.Entity("GithubSync.Infrastructure.Persistence.Models.Label", b =>
                {
                    b.Navigation("IssueLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
